export const COUNTRY_DATA = [
    {
      "code": "ABW",
      "name": "Aruba",
      "continent": "North America",
      "region": "Caribbean",
      "surfacearea": 193.00,
      "indepyear": null,
      "population": 103000,
      "lifeexpectancy": 78.4,
      "gnp": 828.00,
      "gnpold": 793.00,
      "governmentform": "Nonmetropolitan Territory of The Netherlands",
      "headofstate": "Beatrix",
      "capital": 129,
      "code2": "AW"
    },
    {
      "code": "AFG",
      "name": "Afghanistan",
      "continent": "Asia",
      "region": "Southern and Central Asia",
      "surfacearea": 652090.00,
      "indepyear": 1919,
      "population": 22720000,
      "lifeexpectancy": 45.9,
      "gnp": 5976.00,
      "gnpold": null,
      "governmentform": "Islamic Emirate",
      "headofstate": "Mohammad Omar",
      "capital": 1,
      "code2": "AF"
    },
    {
      "code": "AGO",
      "name": "Angola",
      "continent": "Africa",
      "region": "Central Africa",
      "surfacearea": 1246700.00,
      "indepyear": 1975,
      "population": 12878000,
      "lifeexpectancy": 38.3,
      "gnp": 6648.00,
      "gnpold": 7984.00,
      "governmentform": "Republic",
      "headofstate": "José Eduardo dos Santos",
      "capital": 56,
      "code2": "AO"
    },
    {
      "code": "AIA",
      "name": "Anguilla",
      "continent": "North America",
      "region": "Caribbean",
      "surfacearea": 96.00,
      "indepyear": null,
      "population": 8000,
      "lifeexpectancy": 76.1,
      "gnp": 63.20,
      "gnpold": null,
      "governmentform": "Dependent Territory of the UK",
      "headofstate": "Elisabeth II",
      "capital": 62,
      "code2": "AI"
    },
    {
      "code": "ALB",
      "name": "Albania",
      "continent": "Europe",
      "region": "Southern Europe",
      "surfacearea": 28748.00,
      "indepyear": 1912,
      "population": 3401200,
      "lifeexpectancy": 71.6,
      "gnp": 3205.00,
      "gnpold": 2500.00,
      "governmentform": "Republic",
      "headofstate": "Rexhep Mejdani",
      "capital": 34,
      "code2": "AL"
    }
]